name: Test Release Build

on:
  pull_request:
    paths:
      - 'notion_dev/**'
      - 'setup.py'
      - 'pyproject.toml'
      - 'MANIFEST.in'
  push:
    tags:
      - 'v*'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Check package
      run: |
        twine check dist/*
        # Check package size
        SIZE=$(du -h dist/*.whl | cut -f1)
        echo "Package size: $SIZE"
    
    - name: Test installation
      run: |
        # Install the package with its dependencies
        pip install dist/*.whl
        # Just check if the command exists, don't run it
        which notion-dev
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/
        retention-days: 7